### PR TITLE
fix(rule):  don't check keyup events for some elements

### LINKED ISSUE #771: bug: template-click-events-have-key-events: Exclude interactive elements
Make sure that interactive elements like button are excluded

### PR DESCRIPTION
**Pull request by mohammedzamakhan**
fixes #771

### CODE REVIEW

File: src/templateClickEventsHaveKeyEventsRule.ts [hunk 1]
```diff
@@ -37,6 +43,21 @@ class TemplateClickEventsHaveKeyEventsVisitor extends BasicTemplateAstVisitor {
     if (!hasClick) {
       return;
     }
+
+    if (domElements.indexOf(el.name) === -1) {
```
Comment (mgechev) [inline src/templateClickEventsHaveKeyEventsRule.ts]: How many elements do we have in `domElements`? This linear check might be too slow. If we keep it as a set, the check would be `O(1)`.

File: src/util/attributesComparator.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
+import { ElementAst, BoundElementProperty, AttrAst } from '@angular/compiler';
+import { getAttributeValue } from './getAttributeValue';
+import { getLiteralValue } from './getLiteralValue';
+
+function attributesComparator(baseAttributes: any = [], el: ElementAst): boolean {
+  const attributes: Array<AttrAst | BoundElementProperty> = [].concat(...(el.attrs as any), ...(el.inputs as any));
```
Comment (mgechev) [inline src/util/attributesComparator.ts]: I'd suggest to refactor it to use sets/maps, so we can drop the quadratic check to a linear one.

File: src/util/isInteractiveElement.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
+import { dom, elementRoles, roles } from 'aria-query';
+
+import { AXObjects, elementAXObjects } from 'axobject-query';
+
+import attributesComparator from './attributesComparator';
+import { ElementAst } from '@angular/compiler';
+
+const domKeys = [...(<string[]>Array.from(dom.keys()))];
```
Comment (mgechev) [inline src/util/isInteractiveElement.ts]: `(<string[]>Array.from(dom.keys()))`, this should be enough. No need to spread the array into another one

File: src/util/isInteractiveElement.ts [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+const roleKeys: any = [...(<string[]>Array.from(roles.keys()))];
+const elementRoleEntries = [...Array.from(elementRoles)];
+
+const nonInteractiveRoles = new Set(
+  roleKeys.filter(name => {
+    const role = roles.get(name);
+    return !role.abstract && !role.superClass.some(classes => classes.indexOf('widget') !== 0);
```
Comment (mgechev) [inline src/util/isInteractiveElement.ts]: Maybe `every` would be better in this case

File: src/util/isInteractiveElement.ts [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+      'toolbar'
+    )
+    .filter(name => {
+      const role = roles.get(name);
+      return !role.abstract && role.superClass.some(classes => classes.indexOf('widget') !== 0);
+    })
+);
+
+const nonInteractiveElementRoleSchemas = elementRoleEntries.reduce((accumulator: any, [elementSchema, roleSet]: any) => {
+  if ([...Array.from(roleSet)].every((role): boolean => nonInteractiveRoles.has(role))) {
```
Comment (mgechev) [inline src/util/isInteractiveElement.ts]: Same with the spread here.

File: src/templateClickEventsHaveKeyEventsRule.ts (hunk 1 above)
Comment (mohammedzamakhan) [reply src/templateClickEventsHaveKeyEventsRule.ts]: 129 elements

File: src/util/getAttributeValue.ts [hunk 6]
```diff
@@ -7,6 +8,6 @@ export const getAttributeValue = (element: ElementAst, property: string) => {
     return attr.value;
   }
   if (input) {
-    return (<any>input.value).ast.value;
+    return (<any>input.value).ast.value || PROPERTY;
```
Comment (rafaelss95) [inline src/util/getAttributeValue.ts]: Let's try to avoid these `any` casts.

You can do something like this instead:

```
if (!input || !(input.value instanceof ASTWithSource) || !(input.value.ast instanceof LiteralPrimitive)) {
  return null/undefined;
}

return input.value.ast.value;
```

File: src/util/attributesComparator.ts (hunk 2 above)
Comment (rafaelss95) [reply src/util/attributesComparator.ts]: Also, if possible, can we remove these `any` casts?

File: src/util/isInteractiveElement.ts [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+  })
+);
+
+const interactiveRoles: any = new Set(
+  []
+    .concat(
+      roleKeys,
+      // 'toolbar' does not descend from widget, but it does support
+      // aria-activedescendant, thus in practice we treat it as a widget.
+      // @ts-ignore
```
Comment (rafaelss95) [inline src/util/isInteractiveElement.ts]: Could you explain why this is necessary?

File: src/util/attributesComparator.ts (hunk 2 above)
Comment (mohammedzamakhan) [reply src/util/attributesComparator.ts]: @rafaelss95 done

@mgechev I have two different arrays, I don't think I can escape the quadratic check here
